  name: rutina de importacion http
  host: devops
  task:
    name: install apache
    hosts: apacheservers
    become: true

  name: instalar apache
  host: devops
  become: true

  task:
    name: install del paquete
    apt:
      name: apache2
      state: present

    name: setup service
    service:
      name: apache2
      state: started
      enable: yes